[package]
name = "ascii"
version = "0.1.0"
edition = "2024"

[dependencies]
jpeg-decoder = "0.3.1"
ffmpeg-next = { version = "7.1", features = [
    "format",
    "codec",
    "software-resampling",
    "software-scaling",
] }
cpal = "0.15.3"
ringbuf = "0.2.6"
term_size = "0.3.2"
