[package]
name = "ascii"
version = "0.1.0"
edition = "2024"

[dependencies]
jpeg-decoder = "0.3.1"
ffmpeg-next = { version = "7.1", features = [
    "format",
    "codec",
    "software-resampling",
    "software-scaling",
] }
